[env:esp32dev]
; Defines a build environment named esp32dev
; You can have multiple (e.g. debug/release, different boards)

platform = espressif32@6.10.0
; - Tells PlatformIO:
;    - Use the ESP32 platform
;    - Lock it to version 6.10.0
;    - This platform includes:
; - Toolchain (compiler)
;    - Upload tools
;    - Board definitions
;    - Framework integration glue

board = esp32dev
; - Selects a predefined board config
; - Defines:
;   - CPU type
;   - Flash size/layout
;   - Pin mappings
;   - Upload settings

monitor_speed = 115200
; - Serial monitor baud rate
; - Used on your PC side only when viewing logs

framework = arduino
; re-upload of https://github.com/ricardoquesada/esp32-arduino-lib-builder/releases/download/4.1.0/esp32-bluepad32-4.1.0.zip
; but with package.json's "name" field renamed back to framework-arduinoespressif32

platform_packages =
   framework-arduinoespressif32@https://github.com/maxgerhardt/pio-framework-bluepad32/archive/refs/heads/main.zip